export const GET_ERRORS = "GET_ERRORS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_INSTAGRAM_IMAGES = "GET_INSTAGRAM_IMAGES";
